name: SmartPrice
channels:
- conda-forge
dependencies:
  - python=3.7.7
  - conda
  - pandas
  - matplotlib
  - numpy
  - scikit-learn
  - sklearn
  - pip
  - pickle
  - ebaysdk
  - pip:
    - streamlit
